# 站点名称、简称
site_name: JavaPupile
short_name: JP


# 站长基本信息
authorInfo:
  name: LeoChamp
  # home: https://bento.me/tomartisan
  desc: 一个热爱Java的小学生
  avatar: /images/avatar.jpg

# 默认主题：浅色(day)，深色(night)
read_mode: day

# 首页文章排序方式: 最新在前（-1），最老在前（1）
home_page_sort: -1
# 首页展示多少篇文章
home_article_shown: 10

# 代码高亮配置，采用 hightlight，样式在 css/hightlight/* 定义
highlight_theme: atom-one


# 顶部导航菜单名称和别名配置
## 此处申明的菜单条目，需要和站点根目录下"_config.yml"中分类的配置对应，建议不超过4个。如：
###   default_category: top1
###   category_map:
###     顶部菜单1: top1
###     顶部菜单2: top2
###     顶部菜单3: top3
###     顶部菜单4: top4
menu:
  杂谈: talk
  技术文章: article
  resume: resume

# 最左侧常驻的导航菜单，一般指向 /about 即可
left_nav_menus:
- uri: about
  title: About
  faName: fa-question-circle


# 中间封面信息
middleCover:
  title: Easy to say, show me your code
  description: 这是一个关注技术，同时具有人文关怀的博客
  # 中间封面社交连接
  sns:
    github: https://github.com/liulchcn
    # e-mail: liulch.cn@gmail.com
    # youtube: https://www.youtube.com/@itomartisan


# 站点互动信息连接，如聊天室和捐赠地址
# chatLink: https://t.me/itomartisan
# donateLink: https://buymeacoffee.com/tomartisan


# 文章内容申明
post_declare: 
  enable: true
  desc: 本文内容由LeoChamp创作整理，对全网开源，无论是否以盈利为目的

# 站点创建时间，用于页底动态展示：成立X天
site_creation:
  year: 2024
  fulltime: 22/09/2024

# 托管商信息
serveInfo:
  name: github
  url: https://pages.github.com


# 本地搜索
# 依赖库: https://github.com/theme-next/hexo-generator-searchdb
local_search:
  # if auto, trigger search by changing input
  # if manual, trigger search by pressing enter key or search button
  trigger: auto
  # show top n results per article, show all results by setting to -1
  top_n_per_article: 1
  # unescape html strings to the readable one
  unescape: false

## 网站统计，仅支持Google。需要别的自行修改源码
analytics:
  enable: false
  shortname: tomax

## 网站评论，仅支持Disqus。需要别的自行修改源码
comments:
  enable: true
  configId: 12345

## 微软的clarity服务
clarity:
  enable: false
  configId: 54321

## Google AdSense.
adsense:
  auto: false
  client_id: 
  page_tb_id: 
  archive_id: 
  tags_id: 
  post_inner_id: 
  post_left_id: 
  post_right_id:

